<?php /* if( !in_array( $slug, ['residence-2', 'location', 'location-2'] ) ) : */ ?>



<footer>


</footer>




<!--СКРЫТЫЙ БЛОК MAGNIFIC-POPUP-->
<div class="mfp-hide">
    <form id="forms_om" action="#" name="feedback" data-request="ajax" method="POST">
        <div class="wr-block-form clearfix">
            <h2>Обратная связь</h2>
            <p>Заполните все поля и нажмите отправить. Менеджер ответит Вам в течение 10 минут.</p>
            <div class="form-left">
                <div class="input">
                    <i></i>
                    <input type="text" name="uname" placeholder="Ваше имя" required="required">
                </div>
                <div class="input">
                    <i></i>
                    <input type="tel" name="uphone" placeholder="Ваш телефон" required="required">
                </div>
                <div class="input">
                    <i></i>
                    <input type="email" name="uemail" placeholder="Ваш e-mail">
                </div>
            </div>
            <div class="form-right">
                <textarea name="umsg" placeholder="Введите комментарий или вопрос..."></textarea>
            </div>
        </div>
        <div class="form-button">
            <button>Отправить запрос</button>
        </div>

        <div class="logo-ev">
            <a href="#"><img src="<?= getBaseUrl(); ?>/images/logoEV.png" alt=""></a>
            <p>&copy; Rich’Art Club 2016</p>
        </div>
    </form>
</div>


<script type="text/javascript" src="<?= getBaseUrl(); ?>/js/libs/jquery-3.1.1.min.js"></script>
<script type="text/javascript" src="<?= getBaseUrl(); ?>/js/libs/jquery.maskedinput.js"></script>
<script type="text/javascript" src="<?= getBaseUrl(); ?>/js/libs/jquery.magnific-popup.min.js"></script>
<script type="text/javascript" src="<?= getBaseUrl(); ?>/js/libs/jquery.malihu.PageScroll2id.min.js"></script>
<script type="text/javascript" src="<?= getBaseUrl(); ?>/js/libs/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="<?= getBaseUrl(); ?>/js/slick/slick.min.js"></script>
<script type="text/javascript" src="<?= getBaseUrl(); ?>/js/main.js"></script>


</body>

</html>