<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<meta name="description" content="&laquo;Rich'Art&raquo; - клубный дом в историческом центре Санкт-Петербурга. Дом уже сдан. Осталось мало квартир - поторопитесь. Закрытый двор. Подземный паркинг.">
	<title>Rich'Art</title>
	<link rel="stylesheet" type="text/css" href="<?= getBaseUrl(); ?>/js/slick/slick.css"/>
	<link rel="stylesheet" type="text/css" href="<?= getBaseUrl(); ?>/js/slick/slick-theme.css"/>
	<link rel="stylesheet" type="text/css" href="<?= getBaseUrl(); ?>/css/magnific-popup.css"/>
	<link rel="stylesheet" href="<?= getBaseUrl(); ?>/css/general.css" />
	<link rel="stylesheet" href="<?= getBaseUrl(); ?>/css/customer.css" />
</head>
<body>